INSERT INTO countries (name) VALUES
-- Asia
('Afghanistan'),
('Armenia'),
('Azerbaijan'),
('Bahrain'),
('Bangladesh'),
('Bhutan'),
('Brunei'),
('Cambodia'),
('China'),
('Georgia'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Israel'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Lebanon'),
('Malaysia'),
('Maldives'),
('Mongolia'),
('Myanmar (Burma)'),
('Nepal'),
('North Korea'),
('Northern Mariana Islands'),
('Oman'),
('Pakistan'),
('Philippines'),
('Qatar'),
('Russia'),
('Saudi Arabia'),
('South Korea'),
('Sri Lanka'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Timor-Leste'),
('Thailand'),
('Turkey'),
('Turkmenistan'),
('United Arab Emirates'),
('Uzbekistan'),
('Vietnam'),
('Yemen'),

-- Africa
('Angola'),
('Burundi'),
('Benin'),
('Burkina Faso'),
('Botswana'),
('Central African Rep.'),
('Côte d''Ivoire'),
('Cameroon'),
('Dem. Rep. Congo'),
('Congo'),
('Djibouti'),
('Algeria'),
('Egypt'),
('Eritrea'),
('Ethiopia'),
('Gabon'),
('Ghana'),
('Guinea'),
('Gambia'),
('Guinea-Bissau'),
('Eq. Guinea'),
('Kenya'),
('Liberia'),
('Libya'),
('Lesotho'),
('Morocco'),
('Madagascar'),
('Mali'),
('Mozambique'),
('Mauritania'),
('Malawi'),
('Namibia'),
('Niger'),
('Nigeria'),
('Rwanda'),
('Western Sahara'),
('Sudan'),
('South Sudan'),
('Senegal'),
('Sierra Leone'),
('Eswatini'),
('Chad'),
('Togo'),
('Tunisia'),
('Tanzania'),
('Uganda'),
('South Africa'),
('Zambia'),
('Zimbabwe'),
('Somalia'),

-- North America
('Alaska'),
('Antigua and Barbuda'),
('Antilles'),
('Aruba'),
('Bahamas'),
('Barbados'),
('Belize'),
('British Virgin Islands'),
('Canada'),
('Caribbean Netherlands'),
('Cayman Islands'),
('Costa Rica'),
('Cuba'),
('Curaçao'),
('Dominica'),
('Dominican Republic'),
('El Salvador'),
('Greenland'),
('Grenada'),
('Guatemala'),
('Guam'),
('Haiti'),
('Hawaii'),
('Honduras'),
('Jamaica'),
('Martinique'),
('Mexico'),
('Montserrat'),
('Nicaragua'),
('Panama'),
('Puerto Rico'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Trinidad and Tobago'),
('Turks and Caicos Islands'),
('United States'),
('U.S. Virgin Islands'),

-- South America
('Argentina'),
('Bolivia'),
('Brazil'),
('Chile'),
('Colombia'),
('Ecuador'),
('Falkland Islands'),
('French Guiana'),
('Guyana'),
('Paraguay'),
('Peru'),
('Suriname'),
('Uruguay'),
('Venezuela'),

-- Antarctica


-- Europe
('Albania'),
('Austria'),
('Belgium'),
('Bulgaria'),
('Bosnia and Herzegovina'),
('Belarus'),
('Germany'),
('Denmark'),
('Estonia'),
('Finland'),
('France'),
('Greece'),
('Croatia'),
('Hungary'),
('Ireland'),
('Iceland'),
('Italy'),
('Luxembourg'),
('Latvia'),
('Lithuania'),
('Moldova'),
('Macedonia'),
('Montenegro'),
('Netherlands'),
('Norway'),
('Poland'),
('Portugal'),
('Romania'),
('Serbia'),
('Slovakia'),
('Svalbard'),
('Switzerland'),
('Slovenia'),
('Sweden'),
('Ukraine'),
('United Kingdom'),
('Spain'),
('Cyprus'),
('Czechia'),
('Malta'),
('Kosovo'),

-- Oceania
('Australia'),
('Fiji'),
('New Caledonia'),
('New Zealand'),
('Papua New Guinea'),
('Solomon Islands'),
('Vanuatu')
;